sudo: required
branches:
    except:
        - /^phabricator/base/.*$/

matrix:
    include:

        # Android
        - os: linux
          language: android
          compiler: clang
          env:
              - NDK_VERSION=r10e
              - API_LEVEL=17
          android:
              components:
                  - android-22
                  - build-tools-23.0.1
          install: ./scripts/ci/install-android-dependencies
          script:  ./scripts/ci/build-android

        # Linux
        - os: linux
          language: cpp
          dist: trusty
          compiler: clang
          install: ./scripts/ci/install-linux-dependencies
          script:  ./scripts/ci/build-linux
          after_success: bash <(curl -s https://codecov.io/bash) -x "llvm-cov-3.8 gcov"

        ######### Xcode #########
        # XCODE_TARGET isn't used by any of the scripts, but helps make the
        # build matrix a little more readable on Travis.

        # MacOS
        - os: osx
          language: cpp
          osx_image: xcode8
          env:     XCODE_TARGET=macos
          install: ./scripts/ci/install-xcode-dependencies
          script:  ./scripts/ci/build-macos
          after_success: bash <(curl -s https://codecov.io/bash)

        # iPhone
        - os: osx
          language: cpp
          osx_image: xcode8
          env:     XCODE_TARGET=iphoneos
          install: ./scripts/ci/install-xcode-dependencies
          script:  ./scripts/ci/build-iphoneos

        # AppleTV
        - os: osx
          language: cpp
          osx_image: xcode8
          env:     XCODE_TARGET=appletvos
          install: ./scripts/ci/install-xcode-dependencies
          script:  ./scripts/ci/build-appletvos
