#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$script_dir/install-common-dependencies

cd $script_dir/../..

# makedepend for OpenSSL
sudo apt-get update
sudo apt-get install -y xutils-dev
sudo apt-get install unzip

####### Android NDK toolchain #######

android_root=$script_dir/../../toolchains/android

toolchain_destination=$android_root/$NDK_VERSION/android-$API_LEVEL/scraps-toolchain

if [[ -d $toolchain_destination ]] ; then
    echo "Android NDK toolchain already present, skipping installation"
    exit 0
fi

mkdir -p $android_root

cleanup() {
    rm -rf $script_dir/../../temp                 2>/dev/null || true
    rm -rf $android_root/android-ndk-$NDK_VERSION 2>/dev/null || true
}

trap cleanup EXIT TERM INT

mkdir -p temp
(
    cd temp
    echo "Downloading ndk; this may take a while..."
    curl -O https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux-x86_64.zip
    echo "Extracting ndk; this may take a while..."
    unzip android-ndk-$NDK_VERSION-linux-x86_64.zip -d $android_root > /dev/null
)

$android_root/android-ndk-$NDK_VERSION/build/tools/make_standalone_toolchain.py \
    --arch=arm \
    --api=$API_LEVEL \
    --stl=libc++ \
    --install-dir=$toolchain_destination
