#!/bin/bash -e

if [[ ! -z $AWS_ACCESS_KEY_ID ]] && [[ ! -z $CACHE_BUCKET ]] ; then
    echo '{"build-caches": ["s3://'$CACHE_BUCKET'"]}' > ~/.needyconfig
fi

pip install --user jinja2 pyyaml colorama

# command line utilities aren't available in PATH on macOS with --user
sudo pip install awscli git+https://github.com/bittorrent/simon.git@master#egg=simon
